# Site settings
title: Barnsley Skunkworks
email: hello@barnsleyskunk.works
description: > # this means to ignore newlines until "baseurl:"
  A small and loosely structured group of people coming together to research and develop innovative technology ideas, prototypes and solutions to town problems in Barnsley, South Yorkshire.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://barnsleyskunk.works" # the base hostname & protocol for your site

github_username: BarnsleySkunkworks

# Build settings
markdown: kramdown
