# Site settings
title: Barnsley Skunkworks
email: hello@barnsleyskunk.works
description: Barnsley Skunkworks is a small and loosely structured group of cross-departmental council employees, coming together to research and develop innovative technology ideas, prototypes and solutions to town issues.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://barnsleyskunk.works" # the base hostname & protocol for your site

github_username: BarnsleySkunkworks

# Build settings
markdown: kramdown
